x-python-app: &python-app
  build: .
  # Si en el futuro agregás un .env para secretos:
  # env_file: .env

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market_events
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  api:
    <<: *python-app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@timescaledb:5432/market_events
    depends_on:
      - kafka
      - timescaledb

  faust-worker:
    <<: *python-app
    command: faust -A src.consumers.agents worker -l info
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@timescaledb:5432/market_events
    depends_on:
      - kafka
      - timescaledb

  producer:
    <<: *python-app
    command: python -m src.producers.kafka_producer
    environment:
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - kafka

volumes:
  zookeeper_data:
  kafka_data:
  timescaledb_data:
