"""init_schema

Revision ID: f51d55843870
Revises:
Create Date: 2026-08-07 14:39:15.375567

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f51d55843870"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("asset_class", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", "timestamp"),
    )
    op.create_index(
        "ix_market_events_symbol_time", "market_events", ["symbol", "timestamp"], unique=False
    )

    op.create_table(
        "ohlcv_candles",
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "timestamp"),
    )
    op.create_index(
        "ix_ohlcv_candles_symbol_time", "ohlcv_candles", ["symbol", "timestamp"], unique=False
    )

    # TimescaleDB Hypertables
    op.execute("SELECT create_hypertable('market_events', 'timestamp');")
    op.execute("SELECT create_hypertable('ohlcv_candles', 'timestamp');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ohlcv_candles_symbol_time", table_name="ohlcv_candles")
    op.drop_table("ohlcv_candles")
    op.drop_index("ix_market_events_symbol_time", table_name="market_events")
    op.drop_table("market_events")
    # ### end Alembic commands ###
