apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    database: market_events
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true
