from src.schemas.enriched_event import EnrichedMarketEvent
from src.schemas.market_event import BaseMarketEvent
from src.transformers.normalization import normalize_symbol


def enrich_event(event: BaseMarketEvent) -> EnrichedMarketEvent:
    """
    Takes a raw market event and applies normalization and stateless enrichment.

    Args:
        event: The raw incoming market event (CryptoEvent, StockEvent, or ForexEvent).

    Returns:
        An EnrichedMarketEvent containing standardized fields and processing metadata.
    """
    # 1. Normalize the symbol based on its asset class
    normalized_sym = normalize_symbol(event.symbol, event.asset_class)

    # 2. Dump the raw event data into a dictionary
    event_data = event.model_dump()

    # 3. Append the new enriched fields
    event_data["normalized_symbol"] = normalized_sym
    # Note: `processed_timestamp` is automatically generated by the default_factory
    # in the EnrichedMarketEvent model upon instantiation.

    # 4. Instantiate and return the enriched event
    return EnrichedMarketEvent(**event_data)
